version: '3'
services:
  node:
    build: 
      context: .
      target: production
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 9090:9000
      - 3333:3000
