services:
  node:
    image: "node:alpine"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - WS_SERVER_PORT=9000
      - EXPRESS_SERVER_PORT=3456
    command: sh -cx "npm ci && node server/index.js"
    ports:
      - 9000:9000
      - 3456:3456
